packages:
  - "packages/canonical"
  - "packages/protocol"
  - "packages/verifier"
  - "packages/fsm"
  - "packages/registries"
  - "packages/conformance-runner"
  - "packages/api"
  # SDK volontairement hors workspace
